# Generated by Django 6.0.1 on 2026-01-25 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_payment", models.DateField(help_text="Укажите дату оплаты", verbose_name="Дата оплаты")),
                ("amount", models.PositiveIntegerField(help_text="Введите сумму оплаты", verbose_name="Сумма оплаты")),
                (
                    "method",
                    models.CharField(
                        choices=[("cash", "наличные"), ("transfer", "перевод на счет")],
                        default="transfer",
                        editable=False,
                        help_text="Выберите способ оплаты",
                        max_length=10,
                        verbose_name="Способ оплаты",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите урок",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="lms.lesson",
                        verbose_name="Урок",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Введите пользователя",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "сourse",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите курс",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="lms.сourse",
                        verbose_name="Курс",
                    ),
                ),
            ],
        ),
    ]
