# Generated by Django 6.0.1 on 2026-02-08 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_subscription_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="сourse",
            new_name="course",
        ),
        migrations.RenameField(
            model_name="subscription",
            old_name="сourse",
            new_name="course",
        ),
    ]
