# Generated by Django 6.0.1 on 2026-02-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_payment_course_alter_subscription_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Введите ссылку на оплату",
                max_length=800,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True, help_text="Введите id сессии", max_length=255, null=True, verbose_name="id сессии"
            ),
        ),
    ]
