# Generated by Django 6.0.1 on 2026-02-08 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_remove_сourse_owner_remove_lesson_сourse_and_more"),
        ("users", "0006_alter_payment_course_alter_subscription_course"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Сourse",
        ),
    ]
