# Generated by Django 5.2.11 on 2026-02-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_delete_сourse"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateField(
                auto_now=True, help_text="Укажите дату последнего изменения", verbose_name="Дата последнего изменения"
            ),
        ),
    ]
