# Generated by Django 5.2.11 on 2026-02-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_course_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Укажите дату и время последнего изменения",
                verbose_name="Дата и время последнего изменения",
            ),
        ),
    ]
